description = "Ubuntu 22.04 Jammy Jellyfish base image with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.20.14"

[build]
  image = "docker.io/paketobuildpacks/build-jammy-base:0.1.168"

[run]
  [[run.images]]
  image = "index.docker.io/paketobuildpacks/run-jammy-base:latest"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
