description = "Ubuntu 22.04 Jammy Jellyfish base image with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.16.1"

[stack]
  build-image = "docker.io/paketobuildpacks/build-jammy-base:0.1.48"
  id = "io.buildpacks.stacks.jammy"
  run-image = "index.docker.io/paketobuildpacks/run-jammy-base:latest"
  run-image-mirrors = []
